### ISSUE TITLE
CreateTrainJob command not found

### ISSUE THREAD

**Issue by JurgenKriel** [CrispyCrafter/cdeep3m-docker#1]
Runtraining.sh needs to locate a folder with augmented data (augdata) and build the trained model in another folder (trainout). When I include the path to these folders as follows:
`sudo docker run -it cdeep:v0.0.1 --numiterations 10000 --gpu 0 ~/cdeep3m-docker/augdata ~/cdeep3m-docker/trainout`
I get the following error:
`./runtraining.sh: line 127: CreateTrainJob.m: command not found
Error, a non-zero exit code (127) was received from: CreateTrainJob.m "/home/jurgen/cdeep3m-docker/augdata" "/home/jurgen/cdeep3m-docker/trainout" "/home/jurgen/cdeep3m-docker/augdata"`

Am I just specifying the path to the training data incorrectly?

**Comment by CrispyCrafter** [comment]
patched the issue. CreateTrainJob. was not part of the PATH
