### ISSUE TITLE
/train/predictout30k/1fm not a directory

### ISSUE THREAD

**Issue by CrispyCrafter** [CrispyCrafter/cdeep3m-docker#2]
Issue found when running the following command. Any advice?
```
docker run -it cdeep3m:v0.0.1 /train/sbem/mitochrondria/xy5.9nm40nmz/30000iterations_train_out  /home/cdeep3m/cdeep3m-1.6.2/mito_testsample/testset/ /train/predictout30k

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
Starting Image Augmentation
Check image size of:
/home/cdeep3m/cdeep3m-1.6.2/mito_testsample/testset/
Reading file: /home/cdeep3m/cdeep3m-1.6.2/mito_testsample/testset/images.081.png
z_blocks =

   1   5

Start up worker to generate packages to process
Start up worker to run prediction on packages
Start up worker to run post processing on packages

To see progress run the following command in another window:

tail -f /train/predictout30k/logs/*.log
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
/train/predictout30k/1fm not a directory
Please use: EnsemblePredictions ./inputdir1 ./inputdir2 ./inputdir3 ./outputdir
ERROR file found. Something went wrong
ERROR, a non-zero exit code (127) received from PreprocessPackage.m 001 01 1fm 1
8
```

**Comment by JurgenKriel** [comment]
The 300000iterations_train_out folder from the cdeep tutorial is actually an already trained model. So you are actually trying to retrain a model here. For normal training you would run
`--runtraining.sh /testdatafolder /outputfolder`
so here it should be something like
`docker run -it cdeep3m:v0.0.1  /home/cdeep3m/cdeep3m-1.6.2/mito_testsample/testset/ /train/predictout30k`

**Comment by CrispyCrafter** [comment]
lets give it a go

**Comment by CrispyCrafter** [comment]
> The 300000iterations_train_out folder from the cdeep tutorial is actually an already trained model. So you are actually trying to retrain a model here. For normal training you would run
> `--runtraining.sh /testdatafolder /outputfolder`
> so here it should be something like
> `docker run -it cdeep3m:v0.0.1 /home/cdeep3m/cdeep3m-1.6.2/mito_testsample/testset/ /train/predictout30k`

Nope. Just giving me the standard usage printout

**Comment by JurgenKriel** [comment]
Maybe try my training data? Its already in hdf5 format

https://drive.google.com/open?id=1SqXCswdCtuC5ci3Qp8mnvROJnx1ReJkH

**Comment by CrispyCrafter** [comment]
> The 300000iterations_train_out folder from the cdeep tutorial is actually an already trained model. So you are actually trying to retrain a model here. For normal training you would run
> `--runtraining.sh /testdatafolder /outputfolder`
> so here it should be something like
> `docker run -it cdeep3m:v0.0.1 /home/cdeep3m/cdeep3m-1.6.2/mito_testsample/testset/ /train/predictout30k`

Why does the official tutorial use three file paths ?? [DemoRun1](https://github.com/CRBS/cdeep3m/wiki/Demorun-1-Running-prediction-with-pre-trained-model)

```
runprediction.sh ~/sbem/mitochrondria/xy5.9nm40nmz/30000iterations_train_out ~/cdeep3m/mito_testsample/testset/ ~/predictout30k
# results are in ~/predictout30k/ensembled
ls ~/predictout30k/ensembled
```

**Comment by JurgenKriel** [comment]
They didn't want to train a new model from scratch because it would take too long, so they retrained an existing model. So the first path is to the pre-trained model. In this link they explain how to use it for your own data to train a model from scratch

https://github.com/CRBS/cdeep3m/wiki/Run-CDeep3M-training-and-prediction

**Comment by JurgenKriel** [comment]
Actually it looks like you confused the training paths with the prediction paths. To run a prediction you need 3 paths. To specify model, testdata and ensembled directory. For runtraining.sh you only need to specify 2 paths

**Comment by JurgenKriel** [comment]
When I did a new build I see you did in fact set it up for runprediction.sh

**Comment by CrispyCrafter** [comment]
> When I did a new build I see you did in fact set it up for runprediction.sh

Fixed

**Comment by CrispyCrafter** [comment]
also check out the docker-compose setup

**Comment by JurgenKriel** [comment]
> also check out the docker-compose setup

having trouble with docker compose
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

**Comment by JurgenKriel** [comment]
So I run the following after the new build:
`sudo docker run -it cdeep3m:latest ~/cdeep3m-docker/train/augdata/ ~/cdeep3m-docker/train/trainout`

But then it does not find the directories:

`octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
error: First argument is not a directory and its supposed to be
error: called from
    run_train at line 39 column 5
    /home/cdeep3m/CreateTrainJob.m at line 26 column 1
Error, a non-zero exit code (1) was received from: CreateTrainJob.m "/home/jurgen/cdeep3m-docker/train/augdata/" "/home/jurgen/cdeep3m-docker/train/trainout" "/home/jurgen/cdeep3m-docker/train/augdata/"`

Also doesn't work for:
`sudo docker run -it cdeep3m:latest  /train/augdata/  /train/trainout`

**Comment by CrispyCrafter** [comment]
> So I run the following after the new build:
> `sudo docker run -it cdeep3m:latest ~/cdeep3m-docker/train/augdata/ ~/cdeep3m-docker/train/trainout`
> 
> But then it does not find the directories:
> 
> `octave: X11 DISPLAY environment variable not set octave: disabling GUI features error: First argument is not a directory and its supposed to be error: called from run_train at line 39 column 5 /home/cdeep3m/CreateTrainJob.m at line 26 column 1 Error, a non-zero exit code (1) was received from: CreateTrainJob.m "/home/jurgen/cdeep3m-docker/train/augdata/" "/home/jurgen/cdeep3m-docker/train/trainout" "/home/jurgen/cdeep3m-docker/train/augdata/"`
> 
> Also doesn't work for:
> `sudo docker run -it cdeep3m:latest /train/augdata/ /train/trainout`

please follow the instructions in the README.

essentially all you need to do is update the docker-compose.yml

```command:  "RUN TRAINING COMMAND HERE" ```

this would look something like this:
```command: /train/augdata /train/trainout```

Noting that you had to download and move your training data to /train/augdata

**Comment by JurgenKriel** [comment]
Thought I should just replace it with runtraining.sh . Will give it another go thanks!

**Comment by CrispyCrafter** [comment]
Build passing and CUDA operational !

```
I1129 17:17:19.742597    86 caffe.cpp:93] FLAGS_gpu.size() = 1
I1129 17:17:19.742738    86 caffe.cpp:96] FLAGS_strings.size() = 1
I1129 17:17:19.742753    86 caffe.cpp:186] Using GPUs 0
I1129 17:17:20.793673    86 solver.cpp:48] Initializing solver from parameters: 
test_iter: 20
test_interval: 20
base_lr: 0.01
display: 3
max_iter: 30000
lr_policy: "poly"
power: 0.8
momentum: 0.9
weight_decay: 0.0005
snapshot: 2000
snapshot_prefix: "/train/trainout/1fm/trainedmodel/1fm_classifer"
solver_mode: GPU
device_id: 0
net: "train_val.prototxt"
average_loss: 16
iter_size: 8
snapshot_format: BINARYPROTO
I1129 17:17:20.793905    86 solver.cpp:91] Creating training net from net file: train_val.prototxt
I1129 17:17:20.796800    86 net.cpp:322] The NetState phase (0) differed from the phase (1) specified by a rule in layer data
I1129 17:17:20.797145    86 net.cpp:322] The NetState phase (0) differed from the phase (1) specified by a rule in layer accuracy_conv
I1129 17:17:20.798512    86 net.cpp:49] Initializing net from parameters: 
```
Ran using default readme instructions.
