### ISSUE TITLE
nvidia error

### ISSUE THREAD

**Issue by JurgenKriel** [CrispyCrafter/cdeep3m-docker#4]
Installed all the cuda drivers and docker-nvidia, but still get this error.

`/home/cdeep3m/trainworker.sh: line 99: nvidia-smi: command not found
cdeep3m_1  | ERROR unable to get count of GPU(s). Is nvidia-smi working?
cdeep3m_1  | ERROR, a non-zero exit code (4) was received from: trainworker.sh --numiterations 10000`
Is it because I have cuda-10 and ubuntu 18.04 installed on my system? 

Running `sudo docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi` shows that docker-nvidia is working succesfully

**Comment by CrispyCrafter** [comment]
please provide the output of 
```
git log  --pretty=oneline
```
this should correspond to 

```
3e5880d4040c3600cf56d6f2cf7b3d06685cd31f (HEAD -> master, origin/master) updated readme
44b9d21f4bb6fd9c979cf687c85872c03e21e1ce updated readme
eac46320cd8190851be4d75f581afe34319937b8 Final commit build passing
41caab0b3efce1085d9582d5dc336de9bf8e4984 changed CUDA version to 9.0
44c5c337d86c64c2d9c24f410744f7ae3c589f3f Updated readme
34dff0e5ed53c3ed9c0d10ca899c6c639cf1d9cd Updated README
05a317b68af5d6b8e1b56242b7629496c598075d Updated README
ddbe519557ff7f289e554e80a2c5dda10bcae79c Updated dockerfile and docker-compose instructions
e56f29cf913c4b136fa8b82a90de63808723f1b4 reverted back to standard entrypoint
b88f62a7bd6021879d17bbe30ace7555a16e119e updated readme
705bb8022e9ed5f59dec083bf1fb03462b412325 patched PATH issue
95271ec072e207141b40ee28c659dcfb2bbd308b update readme
c701cb2405496f5607b02331b3d22f2f9c9c92f6 updated loader
6a4b359ccbaeb2c32274c419acae5e6b6f4d56b5 Initial commit
```

**Comment by JurgenKriel** [comment]
Got the same output:

`3e5880d4040c3600cf56d6f2cf7b3d06685cd31f (HEAD -> master, origin/master, origin/HEAD) updated readme
44b9d21f4bb6fd9c979cf687c85872c03e21e1ce updated readme
eac46320cd8190851be4d75f581afe34319937b8 Final commit build passing
41caab0b3efce1085d9582d5dc336de9bf8e4984 changed CUDA version to 9.0
44c5c337d86c64c2d9c24f410744f7ae3c589f3f Updated readme
34dff0e5ed53c3ed9c0d10ca899c6c639cf1d9cd Updated README
05a317b68af5d6b8e1b56242b7629496c598075d Updated README
ddbe519557ff7f289e554e80a2c5dda10bcae79c Updated dockerfile and docker-compose instructions
e56f29cf913c4b136fa8b82a90de63808723f1b4 reverted back to standard entrypoint
b88f62a7bd6021879d17bbe30ace7555a16e119e updated readme
705bb8022e9ed5f59dec083bf1fb03462b412325 patched PATH issue
95271ec072e207141b40ee28c659dcfb2bbd308b update readme
c701cb2405496f5607b02331b3d22f2f9c9c92f6 updated loader
6a4b359ccbaeb2c32274c419acae5e6b6f4d56b5 Initial commit
`

**Comment by JurgenKriel** [comment]
But when I try a new build it doesn't recognize the nvidia runtime option
`ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.cdeep3m: 'runtime'`

**Comment by CrispyCrafter** [comment]
How did you solve this problem?

**Comment by JurgenKriel** [comment]
Basically just uninstalled and reinstalled all my nvidia drivers, the cuda toolkit, and nvidia-docker.
