### ISSUE TITLE
runprediciton error

### ISSUE THREAD

**Issue by JurgenKriel** [CrispyCrafter/cdeep3m-docker#6]
I didn't previously have this problem, but now when I change the entry point in the dockerfile and update the commands to run the 'runprediction.sh' script I get the following error:

ERROR, a non-zero exit code (127) received from PreprocessPackage.m 001 01 1fm 1
cdeep3m_1 

Has this happened to you before?

**Comment by JurgenKriel** [comment]
The runprediction error seems to stem from an error in the preprocessworker.sh script. Found the following issue in the output log:

/home/cdeep3m/preprocessworker.sh: line 110: /usr/bin/time: No such file or directory

Although that file definitely exists on my system. Any ideas?

**Comment by JurgenKriel** [comment]
Can you remove the /usr/bin/time -p  command in line 110 of preprocessworker.sh and leave the last part as is? so just keep `PreprocessPackage.m "$img_dir" "$out_dir/augimages" $CUR_PKG $CUR_Z $model_name $aug_speed > "$augoutfile" 2>&1`

**Comment by CrispyCrafter** [comment]
I have updated the file as requested.
One thing to note however is that we have now diverged from the main cdeep3m branch. 
Not a breaking change, however we need to test that everything is working fine.

You can go ahead and rebuild the Dockerfile.

**Comment by JurgenKriel** [comment]
Great. I rebuilt it and changed the entry point. Got a new error though

ERROR, a non-zero exit code (127) was received from: caffepredict.sh

It seems to be the same /usr/bin/time issue, this time in predictworker.sh. Can you check in line 124 of predictworker.sh and remove /usr/bin/time. 

Sorry didn't know it was also in the predictworker file

**Comment by CrispyCrafter** [comment]
removed  /usr/bin/time from all instances.

**Comment by CrispyCrafter** [comment]
Updated Dockerfile to build with "time" installed.
Changed cdeep3m source to pull directly from master branch.
